# Generated by Django 4.2.1 on 2023-05-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='learning',
        ),
        migrations.AddField(
            model_name='users',
            name='languages',
            field=models.JSONField(default='{}'),
        ),
    ]
