# Generated by Django 4.2.1 on 2023-05-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_users_learning_users_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='languages',
            field=models.JSONField(default=dict),
        ),
    ]
