# Generated by Django 4.2.1 on 2023-05-31 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_users_uid_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinese',
            name='user_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.users', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='english',
            name='user_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.users', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='french',
            name='user_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.users', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='user_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.users', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='german',
            name='user_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.users', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='japanese',
            name='user_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.users', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='korean',
            name='user_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.users', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_uid', to='base.users', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_uid', to='base.users', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='spanish',
            name='user_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.users', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='systems',
            name='user_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.users', to_field='uid'),
        ),
    ]
