# Generated by Django 4.2.1 on 2023-06-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_chinese_user_uid_alter_english_user_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='currently_playing',
            field=models.TextField(default=str),
        ),
    ]
