# Generated by Django 4.2.1 on 2023-06-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_users_currently_playing'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_systems',
            field=models.JSONField(default=list),
        ),
    ]
