# Generated by Django 4.2.1 on 2023-06-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_users_user_systems'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_genre',
            field=models.JSONField(default=list),
        ),
    ]
