# Generated by Django 4.2.1 on 2023-06-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='time_of_message',
            field=models.CharField(max_length=22),
        ),
    ]
