# Generated by Django 4.2.1 on 2023-06-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_posts_time_of_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='time_of_message',
            field=models.CharField(max_length=100),
        ),
    ]
